// src/data/dwelling/cost/dwelling-cost-context.ts
//
// Generated by tools/dwelling-cost/build-dwelling-cost.py. Do not hand-edit;
// rebuild from owner-downloaded VGV workbooks. Domain counts are optional
// context and no credential is ever written here.

export const DWELLING_COST_CONTEXT = {
  "dataset": "dwelling-cost-context",
  "methodVersion": "dwelling-cost-v1",
  "generatedAt": "2026-07-17T10:16:22+00:00",
  "defaultMaxPrice": 900000,
  "records": []
} as const

export const DWELLING_COST_BY_ID = Object.fromEntries(
  DWELLING_COST_CONTEXT.records.map((record) => [record.id, record]),
)
