#!/usr/bin/env python3
"""Create the compact, read-only Settle Safety runtime context from an audit.

This promotion step deliberately copies no formula into the browser.  The
candidate score remains the pipeline-approved audit value; the runtime file
only carries the display and scoring-adapter fields required by Settle.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_AUDIT = ROOT / "tools/dwelling-safety/generated/dwelling-safety-audit.json"
DEFAULT_MANIFEST = ROOT / "tools/dwelling-safety/generated/dwelling-safety-source-manifest.json"
DEFAULT_OUT = ROOT / "src/data/dwelling/safety/dwelling-safety-context.js"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit", type=Path, default=DEFAULT_AUDIT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    return parser.parse_args()


def runtime_context(audit: dict, manifest: dict) -> dict:
    """Return the minimal, provenance-preserving runtime representation."""
    model = audit["candidateModel"]
    baskets = model["baskets"]
    return {
        "dataset": audit["dataset"],
        "version": audit["version"],
        "status": "approved-runtime-context",
        "generatedAt": audit["generatedAt"],
        "coverage": audit["coverage"],
        "source": {
            "publisher": manifest["source"]["publisher"],
            "datasetUrl": manifest["source"]["officialDatasetUrl"],
            "referencePeriod": manifest["source"]["referencePeriod"],
            "releaseDate": manifest["source"]["releaseDate"],
            "sha256": manifest["source"]["sha256"],
            "retrievedAt": manifest["source"]["retrievedAt"],
            "sourceTable": "Table 03",
        },
        "interpretation": {
            **model["interpretation"],
            "scope": "Comparative Safety context and an opt-in live Settle ranking criterion. It is not a probability of victimisation.",
        },
        "baskets": [{key: basket[key] for key in ("key", "label", "weight")} for basket in baskets],
        "byAreaId": {
            record["id"]: {
                "score": record["candidateSafetyScore"],
                "rank": record["candidateRank"],
                "cohortSize": len(audit["records"]),
                "baskets": {
                    key: {
                        "riskPercentile": value["smoothedRiskPercentile"],
                        "ratePer100kPersonYears": value["smoothedRatePer100kPersonYears"],
                    }
                    for key, value in record["variants"]["lgaGrowthAdjusted"]["baskets"].items()
                },
            }
            for record in audit["records"]
        },
    }


def write_context(context: dict, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(context, indent=2, ensure_ascii=False)
    out.write_text(
        "// Generated by tools/dwelling-safety/promote-safety-context.py. Do not hand-edit.\n"
        f"export const safetyContext = {payload}\n\n"
        "export function safetyFor(areaId) {\n"
        "  return safetyContext.byAreaId[areaId] || null\n"
        "}\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    audit = json.loads(args.audit.read_text(encoding="utf-8"))
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    if audit["status"] != "audit-only" or audit["liveRankingImpact"] != 0:
        raise ValueError("Only an explicit audit-only safety artifact may be promoted.")
    write_context(runtime_context(audit, manifest), args.out)
    print(f"Wrote runtime Safety context for {len(audit['records'])} records to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
